name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies for Functions
        run: npm --prefix ./functions ci

      # 🚀 Eliminamos el paso de "Install Firebase Tools" porque la acción de abajo ya lo incluye.
      # Esto ahorra tiempo y evita conflictos de versiones.

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v15.5.0 # 🚀 Usamos una versión específica en lugar de @master para mayor estabilidad.
        with:
          args: deploy --only functions,hosting --project premiertraslados-31ee2 # 🚀 Forzamos el ID del proyecto aquí.
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: premiertraslados-31ee2 # 🚀 Definimos explícitamente el ID para evitar la duplicación automática.