name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies for Functions
        run: npm --prefix ./functions ci

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v15.5.0
        with:
          # 🛠️ Eliminamos --project de los args para evitar el error de ruta duplicada
          args: deploy --only functions,hosting
        env:
          # ✅ Usamos PROJECT_ID como variable de entorno, es más limpio para esta acción
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: premiertraslados-31ee2
