name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies for Functions
        run: npm --prefix ./functions ci

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v15.5.0
        with:
          # 🚀 QUITAMOS el flag --project de aquí para que use el del archivo .firebaserc
          args: deploy --only functions,hosting
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          # 🚀 NUNCA agregues PROJECT_ID aquí si usas una Service Account Key